const items = [
    {
        id: 0,
        name: "Winter Blanket",
        price: 25,
        description: "A cozy fleece blanket reserved for donation to a homeless shelter or a family in need",
        img: "../img/WinterBlanket.png",
        numUnit: 0,
    },
    {
        id: 1,
        name: "Meal Voucher",
        price: 10,
        description: "Covers one hot, nutritious meal for someone in need (e.g. in a soup kitchen)",
        img: "../img/meal.png" ,
        numUnit: 0,
    },
    {
        id: 2,
        name: "School Kit",
        price: 40,
        description: "A backpack filled with essential school supplies (notebooks, pens, pencils, eraser, ruler)",
        img: "../img/school.png",
        numUnit: 0,
    },
    {
        id: 3,
        name: "Hygiene Pack",
        price: 15,
        description: "Soap, sanitary items — helps people in crisis situations maintain hygiene and dignity",
        img: "../img/hygiene.png",
        numUnit: 0,
    },
    {
        id: 4,
        name: "Medical kit",
        price: 30,
        description: "Health items (bandages, antiseptics, first aid supplies) — to support local clinics",
        img: "../img/first-aid.png",
        numUnit: 0,
    },
    {
        id: 5,
        name: "Winter Set",
        price: 50,
        description: "A warm coat, hat, gloves and scarf — reserved for a child who needs winter clothes",
        img: "../img/winter-clothing.png",
        numUnit: 0,
    },
    {
        id: 6,
        name: "Care Packag",
        price: 35,
        description: "Diapers, baby formula, wipes, baby clothes — to support new parents in need",
        img: "../img/baby.png",
        numUnit: 0,
    },
    {
        id: 7,
        name: "Emergency Shelter",
        price: 100,
        description: "Helps cover an overnight stay (room, bedding, basic amenities)",
        img: "../img/emergency.png",
        numUnit: 0,
    },
    {
        id: 8,
        name: "Holiday Gift",
        price: 20,
        description: "A small festive gift (toy/book, chocolates) to be delivered to children in orphanages",
        img: "../img/gift.png",
        numUnit: 0,
    },
    {
        id: 9,
        name: "Clean Water",
        price: 60,
        description: "Includes water purification tablets or filters, jerry can, basic hygiene supplies",
        img: "../img/Water.png",
        numUnit: 0,
    },
    {
        id: 10,
        name: "Pet Donation",
        price: 25,
        description: " Provides food, blankets, and basic medical care for pets in animal shelters",
        img: "../img/pet.png",
        numUnit: 0,
    },
    {
        id: 11,
        name: "Garden Support",
        price: 45,
        description: "Funds seeds, tools, and soil for local community garden",
        img: "../img/garden.png",
        numUnit: 0,
    },

]